# Motor Trend Cars - Linear Regression


## User Guide

You have to select a regresor  for MPG and application will show to you:

### Regression
> - Scatterplot in case of variable it continuous
> - Boxplot in case of variable it discrete.

### Correlation 
> - Correlation between the variables in matrix form visualized in different color.

### Clustering
>- Clustering done among the different types of car in the data set.



## Executive Summary
This application try to answer specific question regarding the cars's relationship between miles per galon (MPG) and other variables in dataset. For this we have the folowing database:

> Motor Trend Car Road Tests: The data was extracted from the 1974 Motor Trend US magazine, and comprises fuel consumption and 10 aspects of automobile design and performance for 32 automobiles (1973-74 models)
This aplication show scaterplot graphics and tendence line retulting of applying linear regression to a mtcars dataset 

### Data Description Table

The field in the data have the following meaning:

  Variable | Description 
  :-------:|:---------------
  mpg      |Miles/(US) gallon        
  cyl      |Number of cylinders      
  disp     |Displacement (cu.in.)   
  hp       |Gross horsepower         
  drat     |Rear axle ratio          
  wt       |Weight (lb/1000)         
  qsec     |1/4 mile time            
  vs       |V/S             
  am       |Transmission (0 = automatic, 1 = manual)
  gear     |Number of forward gears
  carb     |Number of carburetors 


### Data Sample

```{r}
head(mtcars)
```
